/**
 * DATABASE GURU & PEMBAGIAN MURID LENGKAP (339 SISWA)
 * Berdasarkan Konversi DaftarMuridActivity.kt
 * SD Teladan Yogyakarta
 */

const dbGuru = { 
    "Pak Tebe": "020694", "Pak Yusuf": "040393", "Bu Arrum": "280700", 
    "Pak Irhas": "100801", "Bu Acha": "110499", "Pak Adieb": "140491", 
    "Bu Rifa": "030198", "Pak Anas": "260797", "Bu Mela": "220896", 
    "Bu Ina": "070593", "Pak Hilmi": "020493", "Pak Oky": "121096" 
};

const dbMuridGuru = {
    "Pak Oky": [
        {n: "Ahmad Yusuf Danisworo", k: "Kelas 1A", t: "Reguler"},
        {n: "Abdullah Hamim Harimurti", k: "Kelas 1A", t: "Reguler"},
        {n: "Adiba Shakila Qorri Aina Ahmad", k: "Kelas 1A", t: "Reguler"},
        {n: "Amanullah Zain", k: "Kelas 1A", t: "Reguler"},
        {n: "Kaivan Elvano Bimantoro", k: "Kelas 1A", t: "Reguler"},
        {n: "Kaleena Ayudhya Ramadhani", k: "Kelas 1A", t: "Reguler"},
        {n: "Osvaldy Rishad Andriyanto", k: "Kelas 1A", t: "Reguler"},
        {n: "Rivero Syam Zafran", k: "Kelas 1A", t: "Reguler"},
        {n: "Shazfa Alrafailah Ahmadi", k: "Kelas 1A", t: "Reguler"},
        {n: "Skyleen Aruna Seiranala Salsabilla", k: "Kelas 1A", t: "Reguler"},
        {n: "Aksara Pendar Andaru", k: "Kelas 2C", t: "Reguler"},
        {n: "Alesha Almahyra Jingga", k: "Kelas 2C", t: "Reguler"},
        {n: "Aretha Cantyana Zyan", k: "Kelas 2C", t: "Reguler"},
        {n: "Fabian Azka Atharizqy Pamungkas", k: "Kelas 2C", t: "Reguler"},
        {n: "Gibran Radhika Wiratama", k: "Kelas 2C", t: "Reguler"},
        {n: "Ihda Aiyra Putrirazu", k: "Kelas 2C", t: "Reguler"},
        {n: "Javas Pandhega Mahfie", k: "Kelas 2C", t: "Reguler"},
        {n: "Kaivan Kamil Setyawijaya", k: "Kelas 2C", t: "Reguler"},
        {n: "Kautsar Nafi Al Qarni", k: "Kelas 2C", t: "Reguler"},
        {n: "Rr. Nayla Tribhuana Tunggadewi", k: "Kelas 2C", t: "Reguler"},
        {n: "Myesha Afsheen Adeeva", k: "Kelas 3A", t: "Reguler"},
        {n: "Nurani Merah Merona", k: "Kelas 3A", t: "Reguler"},
        {n: "R. Danish Satya Kumarajendra", k: "Kelas 3A", t: "Reguler"},
        {n: "Yusuf Haidar Fadil Pratama", k: "Kelas 3A", t: "Reguler"},
        {n: "Nafia Nuha Yudhanto", k: "Kelas 3B", t: "Reguler"},
        {n: "Nafasya Ashima Radisty", k: "Kelas 3C", t: "Reguler"},
        {n: "Keyan Amar Ruqee", k: "Kelas 3D", t: "Reguler"},
        {n: "Alveno Azzam Jatmiko", k: "Kelas 3D", t: "Reguler"},
        {n: "Luna Mikayla Kusuma", k: "Kelas 3D", t: "Reguler"},
        {n: "Adiba Ayunazahra Mahendra", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Afthara Yodya Wishaka", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Alesha Sofia Latif", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Altaff Falah Hamizan Maasi", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Annisa Almahyra", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Arsyila Jehan Naira", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Arvino Muhammad Nazril Khalif", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Attila Nadhif Iskandar", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Azalea Najma Orlin", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Bu Ina": [
        {n: "Abrisam Reynand Putra Mudhita", k: "Kelas 1B", t: "Reguler"},
        {n: "Agha Ahnaf Arrayyan", k: "Kelas 1B", t: "Reguler"},
        {n: "Andi Azka Raffasya Rum", k: "Kelas 1B", t: "Reguler"},
        {n: "Arraya Banyu Manggala Kunadi", k: "Kelas 1B", t: "Reguler"},
        {n: "Auriga Rheandra Tavarino", k: "Kelas 1B", t: "Reguler"},
        {n: "Azzam Abdullah Taftazani", k: "Kelas 1B", t: "Reguler"},
        {n: "Deara Shahia Anindri", k: "Kelas 1B", t: "Reguler"},
        {n: "Ersyila Saibuyun Wirson", k: "Kelas 1B", t: "Reguler"},
        {n: "Nesya Anya Zukhrufa", k: "Kelas 1B", t: "Reguler"},
        {n: "Rayhana Al Maheera Ardiansyah", k: "Kelas 1B", t: "Reguler"},
        {n: "Adeeva Soca Kurniawan", k: "Kelas 2D", t: "Reguler"},
        {n: "Adreena Khanza Agmadina Mecca", k: "Kelas 2D", t: "Reguler"},
        {n: "Almira Hilya Alfathunnisa", k: "Kelas 2D", t: "Reguler"},
        {n: "Febby Victoria", k: "Kelas 2D", t: "Reguler"},
        {n: "Gathan Devdaniyal Gunawan", k: "Kelas 2D", t: "Reguler"},
        {n: "Rajasa Maheswara Nopa Putra", k: "Kelas 2D", t: "Reguler"},
        {n: "Razan Uwais Alvarendra", k: "Kelas 2D", t: "Reguler"},
        {n: "Rr. Zhafira Nidan Qinari", k: "Kelas 2D", t: "Reguler"},
        {n: "Salsabila Delisha Putri", k: "Kelas 2D", t: "Reguler"},
        {n: "Upanarima", k: "Kelas 2D", t: "Reguler"},
        {n: "Attila Nadhif Inskandar", k: "Kelas 3A", t: "Reguler"},
        {n: "Atqiya Ashalina Iskandar Alam", k: "Kelas 3B", t: "Reguler"},
        {n: "Ghalibi Sandiaga Riawan", k: "Kelas 3B", t: "Reguler"},
        {n: "Medina Nameera Aji Queendra", k: "Kelas 3B", t: "Reguler"},
        {n: "Arsya Jivi Damario", k: "Kelas 3B", t: "Reguler"},
        {n: "Jasmine Salsabila Chairunnisa", k: "Kelas 3C", t: "Reguler"},
        {n: "Muhammad Naufal Nur Rasyid", k: "Kelas 3C", t: "Reguler"},
        {n: "Nabila Putri", k: "Kelas 3D", t: "Reguler"},
        {n: "Barra Khalil Ayubi", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Beenatya Adya Martanta", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Cataluna Kinarian Bandriananto", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Efwan Raffaza Abidzar", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Farid Abdillah Anindito", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Fatan Divo Laranta", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Ghassani Swarnanindya Riawan", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Kahiyang Arsyfa Putri", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Kieran Sabiraliana Gazala", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Bu Acha": [
        {n: "Adila Muzzahira Sya'ban", k: "Kelas 1C", t: "Reguler"},
        {n: "Ahmad Haidar Abdurrahman Hadi", k: "Kelas 1C", t: "Reguler"},
        {n: "Anindya Rasika Safira", k: "Kelas 1C", t: "Reguler"},
        {n: "Aulia Ibrahim Al Farisi", k: "Kelas 1C", t: "Reguler"},
        {n: "Faraisa Almahyra Hartadi", k: "Kelas 1C", t: "Reguler"},
        {n: "Giandra Yatrisna Afiano", k: "Kelas 1C", t: "Reguler"},
        {n: "Iza Muhana Hasan", k: "Kelas 1C", t: "Reguler"},
        {n: "Raefal Kenan Atharrazka Lukitaningrat", k: "Kelas 1C", t: "Reguler"},
        {n: "Rayhan Fauzi Baskoro", k: "Kelas 1C", t: "Reguler"},
        {n: "Albifarzan Bima Hahijary", k: "Kelas 2D", t: "Reguler"},
        {n: "Arjuna Kenzo El Azzam", k: "Kelas 2D", t: "Reguler"},
        {n: "Azqiara Shaqeena ADisty", k: "Kelas 2D", t: "Reguler"},
        {n: "Haidar Fasha Arsyanendra", k: "Kelas 2D", t: "Reguler"},
        {n: "Hanania Sahi Dhieayu", k: "Kelas 2D", t: "Reguler"},
        {n: "Kayyisa Anandita Maheswari", k: "Kelas 2D", t: "Reguler"},
        {n: "Kunhiro Zain Mangkunegara Nasution", k: "Kelas 2D", t: "Reguler"},
        {n: "Muhammad Faris Hazim Alghazali", k: "Kelas 2D", t: "Reguler"},
        {n: "Sabira Asheeqa Danurdara", k: "Kelas 2D", t: "Reguler"},
        {n: "Altaff Falah Hamizan Maasi", k: "Kelas 3A", t: "Reguler"},
        {n: "Shafaluna Fidelya Hoshi", k: "Kelas 3A", t: "Reguler"},
        {n: "Beenatya Adya Martanta", k: "Kelas 3A", t: "Reguler"},
        {n: "Syadid Alrafaeyza Ahmadi", k: "Kelas 3B", t: "Reguler"},
        {n: "Al Kahfi Hadianto", k: "Kelas 3C", t: "Reguler"},
        {n: "Den Bagus Asta Maheswara", k: "Kelas 3C", t: "Reguler"},
        {n: "Aldhino Alfafarizki Diody", k: "Kelas 3D", t: "Reguler"},
        {n: "R. Zaid Zeyzan Ombara Nahdi", k: "Kelas 3D", t: "Reguler"},
        {n: "Barra Khalil Ayubi", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Beenatya Adya Martanta", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Cataluna Kinarian Bandriananto", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Efwan Raffaza Abidzar", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Farid Abdillah Anindito", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Fatan Divo Laranta", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Ghassani Swarnanindya Riawan", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Kahiyang Arsyfa Putri", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"},
        {n: "Kieran Sabiraliana Gazala", k: "Kelas 3A", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Pak Anas": [
        {n: "Adiba Putri Diandra", k: "Kelas 1C", t: "Reguler"},
        {n: "A'isyah Inara Saputra", k: "Kelas 1C", t: "Reguler"},
        {n: "Akira Miqdam Narendra", k: "Kelas 1C", t: "Reguler"},
        {n: "Alkhalifi Harits Widodo", k: "Kelas 1C", t: "Reguler"},
        {n: "Muzaffar Hamizan Widhiatna", k: "Kelas 1C", t: "Reguler"},
        {n: "Nadia Syafira", k: "Kelas 1C", t: "Reguler"},
        {n: "Rafif Naufal Byantara", k: "Kelas 1C", t: "Reguler"},
        {n: "Rumaisha Kaheesha Hakim", k: "Kelas 1C", t: "Reguler"},
        {n: "Seraphine Keeyona Rianto", k: "Kelas 1C", t: "Reguler"},
        {n: "Zareena Almeera Azkadina Mukhsinun", k: "Kelas 1C", t: "Reguler"},
        {n: "Arshaka Rasendria", k: "Kelas 2A", t: "Reguler"},
        {n: "Azzahra Rizqya Tsany", k: "Kelas 2A", t: "Reguler"},
        {n: "Farhan Fayada Ilmi", k: "Kelas 2A", t: "Reguler"},
        {n: "Hamid Rasyid Prabawa", k: "Kelas 2A", t: "Reguler"},
        {n: "Hisham Dinan Ata Algiza", k: "Kelas 2A", t: "Reguler"},
        {n: "Ilmia Acitya Dahayu", k: "Kelas 2A", t: "Reguler"},
        {n: "Iltizam Husaini Langsa", k: "Kelas 2A", t: "Reguler"},
        {n: "Rumaisha Nada Malayeka", k: "Kelas 2A", t: "Reguler"},
        {n: "Samudra Dharma Adiwangsa", k: "Kelas 2A", t: "Reguler"},
        {n: "Tsaniya Qonita Sambodo", k: "Kelas 2A", t: "Reguler"},
        {n: "Restina Hayyu Kinanti", k: "Kelas 3A", t: "Reguler"},
        {n: "Reynand Gama Alkanzu", k: "Kelas 3A", t: "Reguler"},
        {n: "Syah Fareeza Nabila Ramadani", k: "Kelas 3B", t: "Reguler"},
        {n: "Adiratna Kinasih Priscanara", k: "Kelas 3B", t: "Reguler"},
        {n: "Arkana Rafasyaa Darmawan", k: "Kelas 3B", t: "Reguler"},
        {n: "Dzakiyah Shafaraz Prasetyo", k: "Kelas 3B", t: "Reguler"},
        {n: "Rafasha Shidiq Alfarih", k: "Kelas 3C", t: "Reguler"},
        {n: "Yasmeena Shaqueena Alesha", k: "Kelas 3C", t: "Reguler"},
        {n: "Zalfa Naqiyya Mecca", k: "Kelas 3D", t: "Reguler"},
        {n: "Inara Ashalina Anindri", k: "Kelas 3D", t: "Reguler"},
        {n: "Mikayla Keysha Syaquila Wibowo", k: "Kelas 3D", t: "Reguler"},
        {n: "Abrisam Reynand Alvarendra", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Adam Zaid Mahesvara", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Adiratna Kinasih Priscanara", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Aghnia Zuhrufa Aulia", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Almeera Shahin Ashalina", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Almir Razka Alvaronizam", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Almira Jeslyn Chalondra", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Aretha Naufa Kartika", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Arkana Rafasyaa Darmawan", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Devendra Farzana Ariqin", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Bu Mela": [
        {n: "Aska Danish Kurniawan", k: "Kelas 1A", t: "Reguler"},
        {n: "Azka Ananda Ramadhan", k: "Kelas 1A", t: "Reguler"},
        {n: "Azriel Dhanadipati Alam", k: "Kelas 1A", t: "Reguler"},
        {n: "Barra Aulian Rafisqy", k: "Kelas 1A", t: "Reguler"},
        {n: "Cahaya Al Jannah Martanta", k: "Kelas 1A", t: "Reguler"},
        {n: "Dineshcara Qiancy Fasyin", k: "Kelas 1A", t: "Reguler"},
        {n: "Dzakiyya Laiba Zyva", k: "Kelas 1A", t: "Reguler"},
        {n: "Elshanina Alrafica", k: "Kelas 1A", t: "Reguler"},
        {n: "Kirani Almahyra Shanum", k: "Kelas 1A", t: "Reguler"},
        {n: "Muhammad Gibran Kareem", k: "Kelas 1A", t: "Reguler"},
        {n: "Adiba Shakilla Azzahra", k: "Kelas 2C", t: "Reguler"},
        {n: "Artanabil Daniyal Zahran", k: "Kelas 2C", t: "Reguler"},
        {n: "Azka Amira Rahman", k: "Kelas 2C", t: "Reguler"},
        {n: "Azrina Zahra Putri Ardiyani", k: "Kelas 2C", t: "Reguler"},
        {n: "Brian Ramadhan Aditiyanto", k: "Kelas 2C", t: "Reguler"},
        {n: "Giovanni Kairan Abrisam", k: "Kelas 2C", t: "Reguler"},
        {n: "Mezzangga Amartya Atharani", k: "Kelas 2C", t: "Reguler"},
        {n: "Muhammad Rifqi Alkhalifi", k: "Kelas 2C", t: "Reguler"},
        {n: "Nuansayang Ada Karindha", k: "Kelas 2C", t: "Reguler"},
        {n: "Savaira Khairani Izzatuniswa", k: "Kelas 2C", t: "Reguler"},
        {n: "Annisa Almahyra", k: "Kelas 3A", t: "Reguler"},
        {n: "Al Meera Shahin Ashalina", k: "Kelas 3B", t: "Reguler"},
        {n: "Almir Razka Alvaronizam", k: "Kelas 3B", t: "Reguler"},
        {n: "Aretha Naufa Kartika", k: "Kelas 3B", t: "Reguler"},
        {n: "Ardhana Rakha Dhanurendra", k: "Kelas 3C", t: "Reguler"},
        {n: "Cakrawala Putera Sanjaya", k: "Kelas 3C", t: "Reguler"},
        {n: "Arvand Hanenda Detama", k: "Kelas 3D", t: "Reguler"},
        {n: "Karima Nismara Pratama", k: "Kelas 3D", t: "Reguler"},
        {n: "Muhammad Dirgantara Alnandi P", k: "Kelas 3D", t: "Reguler"},
        {n: "Arsakha Virendra Pratama", k: "Kelas 3D", t: "Reguler"},
        {n: "Arsaka Alindra Pratama", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Arsya Jivi Damario", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Atqiya Ashalina Iskandar Alam", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Axelle Alatas Bintang Kusuma", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Azlan Hamka Wijaya", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Azzalea Zalfa Humaira", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Ben Khalid Ayubi", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Dzakiyah Shafaraz Prasetyo", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Ghalibi Sandiaga Riawan", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Bu Arrum": [
        {n: "Aqlan Haidar Tsaqib", k: "Kelas 1D", t: "Reguler"},
        {n: "Arvino Nazriel Rashaad Fredian", k: "Kelas 1D", t: "Reguler"},
        {n: "Ashalina Anisa Khadija", k: "Kelas 1D", t: "Reguler"},
        {n: "Muhammad Azzam Giandra", k: "Kelas 1D", t: "Reguler"},
        {n: "Pragnya Grahita Nuraisya", k: "Kelas 1D", t: "Reguler"},
        {n: "Qanita Zea Kaylila Rafsanjani", k: "Kelas 1D", t: "Reguler"},
        {n: "Rauffa Yahya Alfatih", k: "Kelas 1D", t: "Reguler"},
        {n: "Resyakilla Noushafarina Putri Novindra", k: "Kelas 1D", t: "Reguler"},
        {n: "Syarifah Hala Farisha Aisha", k: "Kelas 1D", t: "Reguler"},
        {n: "Tsabina Latisya Orlin Fransisco", k: "Kelas 1D", t: "Reguler"},
        {n: "Abdullah Isa Sulistiono", k: "Kelas 2A", t: "Reguler"},
        {n: "Bestarila Benzita Rachdiwasitta Rachman", k: "Kelas 2A", t: "Reguler"},
        {n: "Dimas Ramdhan Nasrullah", k: "Kelas 2A", t: "Reguler"},
        {n: "Felicya Dafina Alka", k: "Kelas 2A", t: "Reguler"},
        {n: "Ibrahim Ali Gaza", k: "Kelas 2A", t: "Reguler"},
        {n: "Kenan Mahija Rupawan", k: "Kelas 2A", t: "Reguler"},
        {n: "Muhammad Arfan Al Fatih", k: "Kelas 2A", t: "Reguler"},
        {n: "Sarah Harharah", k: "Kelas 2A", t: "Reguler"},
        {n: "Syamil Albidhira Pratisara", k: "Kelas 2A", t: "Reguler"},
        {n: "Arvino Muhammad Nazril Khalif", k: "Kelas 3A", t: "Reguler"},
        {n: "Farid Abdillah Anindito", k: "Kelas 3A", t: "Reguler"},
        {n: "Azalea Najma Orlin", k: "Kelas 3A", t: "Reguler"},
        {n: "Alzia Anggun Putri Lesmana", k: "Kelas 3A", t: "Reguler"},
        {n: "Azzalea Zalfa Humaira", k: "Kelas 3B", t: "Reguler"},
        {n: "Azlan Hamka Wijaya", k: "Kelas 3B", t: "Reguler"},
        {n: "R.Ismail Hidayatullah", k: "Kelas 3C", t: "Reguler"},
        {n: "Muhammad Irfan Fatahillah Azzikri", k: "Kelas 3D", t: "Reguler"},
        {n: "Nada Farhana Zayn", k: "Kelas 3D", t: "Reguler"},
        {n: "Kyna Mecca Avicenna", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Medina Nameera Aji Queendra", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Mehdi Arafat", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Muhammad Wahyu Abidzar", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Nafia Nuha Yudhanto", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Olivia Aleshaeda Istiawan", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Rama Najid Abdillah Munandar", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Syadid Alrafaeyza Ahmadi", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"},
        {n: "Syah Fareeza Nabila Ramadani", k: "Kelas 3B", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Pak Tebe": [
        {n: "Freya Safira Yasmin Fitaly", k: "Kelas 1B", t: "Reguler"},
        {n: "Gading Ghazali", k: "Kelas 1B", t: "Reguler"},
        {n: "Ganesh Hamizzhafran", k: "Kelas 1B", t: "Reguler"},
        {n: "Ghassani Zianka Elshanum", k: "Kelas 1B", t: "Reguler"},
        {n: "Hafid Rabbani", k: "Kelas 1B", t: "Reguler"},
        {n: "Muhammad Kalandra Abdillah Waseso", k: "Kelas 1B", t: "Reguler"},
        {n: "Muhammad Oktaf Addyagani", k: "Kelas 1B", t: "Reguler"},
        {n: "Muhammad Said Hadyandhika Purwanto", k: "Kelas 1B", t: "Reguler"},
        {n: "Qiandra Humaira Praditya", k: "Kelas 1B", t: "Reguler"},
        {n: "Sarah Mecca Alexandra", k: "Kelas 1B", t: "Reguler"},
        {n: "Giandra Adyatama Susanto", k: "Kelas 2C", t: "Reguler"},
        {n: "Arshaka Kenzie Ervito", k: "Kelas 2C", t: "Reguler"},
        {n: "Annasya Nadheera Mecca", k: "Kelas 2C", t: "Reguler"},
        {n: "Ahmad Fatta As-Sufi", k: "Kelas 2C", t: "Reguler"},
        {n: "Kayra Shahia Ananta", k: "Kelas 2C", t: "Reguler"},
        {n: "Rafka Aryaputra", k: "Kelas 2C", t: "Reguler"},
        {n: "Afthara Yodya Wishaka", k: "Kelas 3A", t: "Reguler"},
        {n: "Barra Khalil Ayubi", k: "Kelas 3A", t: "Reguler"},
        {n: "Ben Khalid Ayubi", k: "Kelas 3B", t: "Reguler"},
        {n: "Devendra Farzana Ariqin", k: "Kelas 3B", t: "Reguler"},
        {n: "Ardana Kaelan Albar", k: "Kelas 3C", t: "Reguler"},
        {n: "Azni Azarine", k: "Kelas 3C", t: "Reguler"},
        {n: "Nadria Kinandari Adia", k: "Kelas 3C", t: "Reguler"},
        {n: "Muhammad Harun Al Rasyid", k: "Kelas 3D", t: "Reguler"},
        {n: "Al Kahfi Hadianto", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Alyssa Azzahra", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Ardana Kaelan Albar", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Arsakha Muhammad Adrian", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Azni Azarine", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Cakrawala Putera Sanjaya", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Daffa Abhimata Khatulistiwa", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Den Bagus Asta Maheswara", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Elvina Arsyfa Salsabila", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Pak Irhas": [
        {n: "Itzel Arsyila Delphys", k: "Kelas 1C", t: "Reguler"},
        {n: "Nararya Widayaka Listyawan", k: "Kelas 1C", t: "Reguler"},
        {n: "Nayra Mafaza Mukhbita Biantara", k: "Kelas 1C", t: "Reguler"},
        {n: "Ning Laya Pandanmawar", k: "Kelas 1C", t: "Reguler"},
        {n: "R. Dirga Danadyaksa", k: "Kelas 1C", t: "Reguler"},
        {n: "Rania Afsheena Qanita Wahdono", k: "Kelas 1C", t: "Reguler"},
        {n: "Razzan Darpa Yowano", k: "Kelas 1C", t: "Reguler"},
        {n: "Sabriya Bitumina Kinandari", k: "Kelas 1C", t: "Reguler"},
        {n: "Zioshaka Artanabil Pradana", k: "Kelas 1C", t: "Reguler"},
        {n: "Arkan Ghifari Alfarizi Ramadhan", k: "Kelas 2A", t: "Reguler"},
        {n: "Arsa Bhiru Daniswara", k: "Kelas 2A", t: "Reguler"},
        {n: "Aulian Tyaga Barananta", k: "Kelas 2A", t: "Reguler"},
        {n: "Banyubiru Adhyasta Mahanipuna", k: "Kelas 2A", t: "Reguler"},
        {n: "Bianca Putri KInarian", k: "Kelas 2A", t: "Reguler"},
        {n: "Gavindra Abimana", k: "Kelas 2A", t: "Reguler"},
        {n: "Mazaya Tsania Fauziah", k: "Kelas 2A", t: "Reguler"},
        {n: "Sheeran Latishya Naimatama", k: "Kelas 2A", t: "Reguler"},
        {n: "Kahiyang Arsyfa Putri", k: "Kelas 3A", t: "Reguler"},
        {n: "Paundrakarna Adrian", k: "Kelas 3A", t: "Reguler"},
        {n: "Adam Zaid Mahesvara", k: "Kelas 3B", t: "Reguler"},
        {n: "Muhammad Dzaky Yudistira", k: "Kelas 3C", t: "Reguler"},
        {n: "Arsakha Muhammad Adrian", k: "Kelas 3C", t: "Reguler"},
        {n: "Kyna Medina Arscylla", k: "Kelas 3C", t: "Reguler"},
        {n: "Nouman Alaric Rausyanfikri W.", k: "Kelas 3C", t: "Reguler"},
        {n: "Hazira Sauqiya", k: "Kelas 3D", t: "Reguler"},
        {n: "Faza Ahmad Alfarizqi", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Hanief Habibie Oktadio", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Hilmi Ammar Ahmad", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Jasmine Salsabila Chairunnisa", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Keysha Arindra Ramadhani", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Kyna Medina Arscylla", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Muhammad Dzaky Yudistira", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Muhammad Naufal Nur Rasyid", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Nadine Zivana Prabowo", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Pak Yusuf": [
        {n: "Almahyra Shaneisha Anindira Isa S", k: "Kelas 1A", t: "Reguler"},
        {n: "Arkan Anggara Rahmadi", k: "Kelas 1A", t: "Reguler"},
        {n: "Ashalina Yumnaa Naladhipa Sudrajat", k: "Kelas 1A", t: "Reguler"},
        {n: "Aulia Zulfa Muthii'ah", k: "Kelas 1A", t: "Reguler"},
        {n: "Azka Bhumi Ibrahim", k: "Kelas 1A", t: "Reguler"},
        {n: "Khalisha Fahma Zahida", k: "Kelas 1A", t: "Reguler"},
        {n: "Kuntum Adreena Alesha Senja", k: "Kelas 1A", t: "Reguler"},
        {n: "Muhamamd Arsyad Hamzah", k: "Kelas 1A", t: "Reguler"},
        {n: "Muhammad Devan Rafandra", k: "Kelas 1A", t: "Reguler"},
        {n: "Muhammad Haykal Latif", k: "Kelas 1A", t: "Reguler"},
        {n: "Azkia Soraya Azzahra", k: "Kelas 2D", t: "Reguler"},
        {n: "Bingar Samudra Sangkan Pawenang", k: "Kelas 2D", t: "Reguler"},
        {n: "Bramantya Anhar Danavendra", k: "Kelas 2D", t: "Reguler"},
        {n: "Gifagan Rasendria Adnan", k: "Kelas 2D", t: "Reguler"},
        {n: "Hamizan Rafif Murwanto", k: "Kelas 2D", t: "Reguler"},
        {n: "Keisyafa Arga Azzahra", k: "Kelas 2D", t: "Reguler"},
        {n: "Muhammad Arzanka Alqahtani", k: "Kelas 2D", t: "Reguler"},
        {n: "Muhammad Naufal Ghifari Yahya", k: "Kelas 2D", t: "Reguler"},
        {n: "Runako Arsenio Tovani", k: "Kelas 2D", t: "Reguler"},
        {n: "Arsyila Jehan Naira", k: "Kelas 3A", t: "Reguler"},
        {n: "Kyna Mecca Avicenna", k: "Kelas 3B", t: "Reguler"},
        {n: "Aghnia Zuhrufa Aulia", k: "Kelas 3B", t: "Reguler"},
        {n: "Axelle Alatas Bintang Kusuma", k: "Kelas 3B", t: "Reguler"},
        {n: "Keysha Arindra Ramadhani", k: "Kelas 3C", t: "Reguler"},
        {n: "Radika Rafi Radiaskoro", k: "Kelas 3C", t: "Reguler"},
        {n: "Faza Ahmad Alfarizqi", k: "Kelas 3C", t: "Reguler"},
        {n: "Kekira Athaleta Almeera", k: "Kelas 3D", t: "Reguler"},
        {n: "Misha Chairunnisa", k: "Kelas 3D", t: "Reguler"},
        {n: "Fazyan Abyaz Arsen", k: "Kelas 3D", t: "Reguler"},
        {n: "Muhammad Sultan Hafiz", k: "Kelas 3D", t: "Reguler"},
        {n: "Nadria Kinandari Adia", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Nafasya Ashima Radisty", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Nouman Alaric Rausyanfikri Witoyo", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "R.Ismail Hidayatullah", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Radika Rafi Radiaskoro", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Rafasha Shidiq Alfarih", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Rania Nindita Pangaribowo", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Tisya Dea Ashalina", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"},
        {n: "Yasmeena Shaqueena Alesha", k: "Kelas 3C", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Bu Rifa": [
        {n: "Ahmad Rayhan Adyarizki", k: "Kelas 1D", t: "Reguler"},
        {n: "Annisa Misaki Al Hakim", k: "Kelas 1D", t: "Reguler"},
        {n: "Aqilla Mahiska Virendra", k: "Kelas 1D", t: "Reguler"},
        {n: "Elif Andarestya Maylafaisha", k: "Kelas 1D", t: "Reguler"},
        {n: "Gheadhimas Yumna Zaviera", k: "Kelas 1D", t: "Reguler"},
        {n: "Khaulah Salma Nabila", k: "Kelas 1D", t: "Reguler"},
        {n: "Muhammad Zhafran Syathir Wijaya", k: "Kelas 1D", t: "Reguler"},
        {n: "Nur Alula Zahran Rabbani", k: "Kelas 1D", t: "Reguler"},
        {n: "Raffasya Azam Faeza Raharjo", k: "Kelas 1D", t: "Reguler"},
        {n: "Arinda Satya Wicaksono", k: "Kelas 2B", t: "Reguler"},
        {n: "Bryan Xavier Al Ghifari", k: "Kelas 2B", t: "Reguler"},
        {n: "Feerozah Adeeva Rizta", k: "Kelas 2B", t: "Reguler"},
        {n: "Muhammad Darius El Shareef Khayruagung", k: "Kelas 2B", t: "Reguler"},
        {n: "Nashira Yumna Almaodhi", k: "Kelas 2B", t: "Reguler"},
        {n: "Paraduta Bhodrowanto Suryoningrat", k: "Kelas 2B", t: "Reguler"},
        {n: "Ramadhanisa Nur Shahia", k: "Kelas 2B", t: "Reguler"},
        {n: "Reynand Arka Zavier", k: "Kelas 2B", t: "Reguler"},
        {n: "Virendra Gibran Tosca", k: "Kelas 2B", t: "Reguler"},
        {n: "Zyan Abdul Malik", k: "Kelas 2B", t: "Reguler"},
        {n: "Alesha Sofia Latif", k: "Kelas 3A", t: "Reguler"},
        {n: "Kieran Sabiraliana Gazala", k: "Kelas 3A", t: "Reguler"},
        {n: "Olivia Aleshaeda Istiawan", k: "Kelas 3B", t: "Reguler"},
        {n: "Dzakiyah Shafaraz Prasetyo", k: "Kelas 3B", t: "Reguler"},
        {n: "Mehdi Arafat", k: "Kelas 3B", t: "Reguler"},
        {n: "Hanief Habibie Oktadio", k: "Kelas 3C", t: "Reguler"},
        {n: "Raisya Almahyra Hanifa", k: "Kelas 3D", t: "Reguler"},
        {n: "Raden Ajeng Amira Sophia", k: "Kelas 3D", t: "Reguler"},
        {n: "Hafidz Orlando Akbar", k: "Kelas 3D", t: "Reguler"},
        {n: "Aldhino Alfarizki Diody", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Alveno Azzam Jatmiko", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Ardhana Rakha Dhanurendra", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Arsakha Virendra Pratama", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Arvand Hanenda Detama", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Fahiera Salsabila Chairunnisa", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Fazyan Abyaz Arsen", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Hafidz Orlando Akbar", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Hazira Sauqiya", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Pak Hilmi": [
        {n: "Arcello Radeva Kurniawan", k: "Kelas 1D", t: "Reguler"},
        {n: "Keyza Alfarisi Rumi", k: "Kelas 1D", t: "Reguler"},
        {n: "Khalifa Arshaka Setyojati", k: "Kelas 1D", t: "Reguler"},
        {n: "Kynan Azkale Rahman", k: "Kelas 1D", t: "Reguler"},
        {n: "Maheswara Arganta Praditya", k: "Kelas 1D", t: "Reguler"},
        {n: "Maitreya Sakala Prastiyo", k: "Kelas 1D", t: "Reguler"},
        {n: "Maiza Almahyra Putri Yudhistira", k: "Kelas 1D", t: "Reguler"},
        {n: "Muhammad Arniko Ichimoku Mokoku", k: "Kelas 1D", t: "Reguler"},
        {n: "Muhammad Uwais Al Qarni", k: "Kelas 1D", t: "Reguler"},
        {n: "Muhammad Yahya Al Maliq", k: "Kelas 1D", t: "Reguler"},
        {n: "Alexander Dhafin Ghifari Shakeil", k: "Kelas 2B", t: "Reguler"},
        {n: "Alvira Gitania Putri Khariestama", k: "Kelas 2B", t: "Reguler"},
        {n: "Ibrahim Bagaskoro D. Saksama", k: "Kelas 2B", t: "Reguler"},
        {n: "Maulidya Almeera Wilantara", k: "Kelas 2B", t: "Reguler"},
        {n: "Medina Lituhayu Shaleeha Syahyaman", k: "Kelas 2B", t: "Reguler"},
        {n: "Muhammad Muzakki Al Fatih", k: "Kelas 2B", t: "Reguler"},
        {n: "Nayazka Ailean Farizky", k: "Kelas 2B", t: "Reguler"},
        {n: "Raden Kairupan Abduh Humayun", k: "Kelas 2B", t: "Reguler"},
        {n: "Raffasya Achmad Rasya", k: "Kelas 2B", t: "Reguler"},
        {n: "Shanum Almeera Wibowo", k: "Kelas 2B", t: "Reguler"},
        {n: "Cataluna Kinarian Bandriananto", k: "Kelas 3A", t: "Reguler"},
        {n: "Adiba Ayunazahra Mahendra", k: "Kelas 3A", t: "Reguler"},
        {n: "Arsaka Alindra Pratama", k: "Kelas 3B", t: "Reguler"},
        {n: "Rama Najid Abdillah Munandar", k: "Kelas 3B", t: "Reguler"},
        {n: "Muhammad Wahyu Abidzar", k: "Kelas 3B", t: "Reguler"},
        {n: "Alyssa Azzahra", k: "Kelas 3C", t: "Reguler"},
        {n: "Fahiera Salsabila Chairunnisa", k: "Kelas 3D", t: "Reguler"},
        {n: "Inara Ashalina Anindri", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Karima Nismara Pratama", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Kekira Athaleta Almeera", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Ken Luthra Padmanggala", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Keyan Amar Ruqee", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Luna Mikayla Kusuma", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Mikayla Keysha Syaquila Wibowo", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Misha Chairunnisa", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Muhammad Dirgantara Alnandi Putra", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"}
    ],

    "Pak Adieb": [
        {n: "Aeshaa Mikayla Faradeeva", k: "Kelas 1B", t: "Reguler"},
        {n: "Assyifa Shafiyya Linando", k: "Kelas 1B", t: "Reguler"},
        {n: "Chantika Queen Arsyila", k: "Kelas 1B", t: "Reguler"},
        {n: "Hafizhah Acitya Saraswati", k: "Kelas 1B", t: "Reguler"},
        {n: "Haufanhazza Ghaniyandra", k: "Kelas 1B", t: "Reguler"},
        {n: "Kania Fadila", k: "Kelas 1B", t: "Reguler"},
        {n: "Kennan El Zafran", k: "Kelas 1B", t: "Reguler"},
        {n: "Muhammad Ahsan Laksono", k: "Kelas 1B", t: "Reguler"},
        {n: "Muhammad Khaisan Mumtaz", k: "Kelas 1B", t: "Reguler"},
        {n: "Shumaila Shanum Bawono", k: "Kelas 1B", t: "Reguler"},
        {n: "Adrian Wira Muliawan", k: "Kelas 2B", t: "Reguler"},
        {n: "Arondra Karna Dion Adriand", k: "Kelas 2B", t: "Reguler"},
        {n: "Delano Alvarendra Diody", k: "Kelas 2B", t: "Reguler"},
        {n: "Firash Ramadhan Aljunnah Irvani", k: "Kelas 2B", t: "Reguler"},
        {n: "Kinanti Armadani", k: "Kelas 2B", t: "Reguler"},
        {n: "Nesya Ardelia", k: "Kelas 2B", t: "Reguler"},
        {n: "Raina Kayla Alexandera", k: "Kelas 2B", t: "Reguler"},
        {n: "Umar Syafiq Rabbani", k: "Kelas 2B", t: "Reguler"},
        {n: "Efwan Raffaza Abidzar", k: "Kelas 3A", t: "Reguler"},
        {n: "Ghassani Swarnanindya Riawan", k: "Kelas 3A", t: "Reguler"},
        {n: "Alesha Sofia Latif", k: "Kelas 3A", t: "Reguler"},
        {n: "Fatan Divo Laranta", k: "Kelas 3A", t: "Reguler"},
        {n: "Abrisam Reynand Alvarendra", k: "Kelas 3B", t: "Reguler"},
        {n: "Muhammad Harun Al Rasyid", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Muhammad Irfan Fatahillah Azzikri", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Muhammad Sultan Hafiz", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Nabila Putri", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Nada Farhana Zayn", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "R. Zaid Zeyzan Ombara Nahdi", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Raden Ajeng Amira Sophia", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Raisya Almahyra Hanifa", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"},
        {n: "Zalfa Naqiyya Mecca", k: "Kelas 3D", t: "Khusus Tahfidz Kelas 3"}
    ]
};
